WebStockFinder/Controllers/FDHSController.cs
using Alonso.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WinStockFinder.DAL;

namespace WebStockFinder.Controllers
{

    /// <summary>
    /// 
    /// </summary>
    public class FDHSController : Controller
    {
       

        TwstockDAL twstockDAL { get; set; }

        public FDHSController()
        {
            twstockDAL = new TwstockDAL();
        }

        public ActionResult Index()
        {

            return View();
        }

        [HttpPost]
        public JsonResult Index(string chDate, string chDays, string chStock)
        {

            //策略11.最低價格的日期往後抓 價格
            //假設1 / 2價格為10 那麼1/ 2 之後的max價格一定要 > 10 ，相除最好有100 % 以上
            //1 / 2之後的價格 = 20(除法)  1 / 2價格 = 10    =>>> 100 %
            //股票的最低價 = 6 ~29  的股票要有50 % 漲幅
            //股票的最低價 = 30  ~49 的股票要有  50 % 漲幅
            //股票的最低價 = 50~100 的股票 要有30% 的漲幅

            chDate = (DateTime.Now.Year - 1911).ToString() + DateTime.Now.ToString("MMdd");
            string bf360Days = (DateTime.Now.AddDays(-360).Year - 1911).ToString() + DateTime.Now.ToString("MMdd");

            IEnumerable<string>  stocks = twstockDAL. GetOneFileds("  distinct [StockCode]  ", " ");
            var result = new List<WinStockFinder.Model.Twstock>();
            foreach (var stock in stocks)
            {
                string cond = string.Format(" chDate >='{0}' and chDate <='{1}' and  StockCode='{2}' ", bf360Days, chDate, stock);
                var tempData = twstockDAL.GetListArray(cond);

                double? minZ = tempData.Where( i => i.ClosePrice !=0).Min(obj => obj.ClosePrice );
                if (minZ == null) continue;
                

                var minObj = tempData.Where(obj => obj.ClosePrice == minZ).FirstOrDefault();

//                var maxZ = tempData.Max(obj => obj.ClosePrice);
                double? maxZ = tempData.Where(obj =>   Convert.ToInt32( obj.chDate ) >= Convert.ToInt32( minObj.chDate)   ).Max( i => i.ClosePrice);

                double? priceresult = maxZ / minZ;

                priceresult -= 1;

                if (minZ <30 && priceresult > 1.00 )
                {
                    result.Add( new WinStockFinder.Model.Twstock {  StockCode= stock } );
                }

                if (minZ >29 && minZ <=60 && priceresult > 0.45)
                {
                    result.Add(new WinStockFinder.Model.Twstock { StockCode = stock });
                }

                if (minZ >60 && minZ <101 && priceresult > 0.3)
                {
                    result.Add(new WinStockFinder.Model.Twstock { StockCode = stock });
                }



            }


     
        


         

            return Json(result);
        }
    }
}

WebStockFinder/Views/FDHS/Index.cshtml
<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/My97DatePicker/WdatePicker.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/My97DatePicker/skin/WdatePicker.css" rel="stylesheet" />

<h3>股票查詢作業</h3>
<h3>主要查詢可能是黑馬的股票</h3>


<button type="button" class="btn btn-primary" onclick="loadData();">查詢</button>

<table class="table table-bordered ">
    <thead>
        <tr>
            <th>管理</th>

            <th>日期</th>
            <th>收盤價</th>
            <th>漲跌幅</th>
            <th>交易數量</th>
            <th>交易金額</th>
            <th>開盤價</th>
            <th>最高價</th>
            <th>最低價</th>
            <th>股票代號</th>

        </tr>
    </thead>
    <tbody id="tbody"></tbody>
</table>


<script>


    $(document).ready(function () {
        loadData();
    });





    //Load Data function
    function loadData() {






        var postdata = getcond();

      var url =  '@Url.Action("Index", "FDHS")';

        $.post(url, postdata, function (json) {


            var html = '';
            $.each(json, function (i, item) {
                // console.log("第" + i + "个元素：");
                //  console.log(blog);
                html += '<tr>';
                html += '    <td>';
           //     html += '        <a href="/Adnn1n/Twstock/Add/' + item.id + '"><i class="layui-icon">&#xe642;</i> 编辑</a>';
                //html += '        <a href="javascript:void(0);" onclick="del(' + item.id + ')"><i class="layui-icon">&#x1006;</i> 删除</a>';
                html += '    </td>';

                html += '    <td>' + item.chDate + '</td>';
                html += '    <td>' + item.ClosePrice + '</td>';
                html += '    <td>' + item.UpOrDown + '</td>';
                html += '    <td>' + item.TradeCount + '</td>';
                html += '    <td>' + item.TradeMoney + '</td>';
                html += '    <td>' + item.OpenPrice + '</td>';
                html += '    <td>' + item.HightPrice + '</td>';
                html += '    <td>' + item.LowPrice + '</td>';
                html += '    <td>' + item.StockCode + '</td>';


                html += '</tr>';

            })

            $('#tbody').html(html);

        }, 'json');


    }

    /*拼接条件返回postdata*/
    function getcond() {

        var chDate = $("#chDate").val();
        var chDays = $("#chDays").val();
        var chStock = $("#chStock").val();
        var postdata = { chDate: chDate, chDays: chDays, chStock: chStock };
        return postdata;
    }


</script>