WebStockFinder/Controllers/TwstockController.cs
using Alonso.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WinStockFinder.DAL;
namespace WebStockFinder.Controllers
{
    public class TwstockController : Controller
    {
        TwstockDAL TwstockDAL { get; set; }
        FutureStockDAL futureStockDAL { get; set; }

        public TwstockController()
        {
            TwstockDAL = new TwstockDAL();
            futureStockDAL = new FutureStockDAL();
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Index(string chDate, string chDays, string chStock)
        {
            if (string.IsNullOrEmpty(chDate))
            {
                chDate = (DateTime.Now.Year - 1911).ToString() + DateTime.Now.ToString("MMdd");
            }
            if (string.IsNullOrEmpty(chDays))
            {
                chDays = "60";
            }
            var result = new List<WinStockFinder.Model.Twstock>();
            string where = " 1=1 ";
            WhereClausesBuilder whereClausesBuilder = new WhereClausesBuilder();
            whereClausesBuilder.appendCriteriaText(chDate, " chDate = '{0}'", ref where);
            whereClausesBuilder.appendCriteriaText(chStock, " chStock = '{0}'", ref where);
            whereClausesBuilder.appendCriteriaText(chStock, " chStock = '{0}'", ref where);
            string cond1 = where + "  and  ClosePrice > 50 and  ClosePrice < 101 ";
            string cond2 = where + "  and  ClosePrice > 150 and  ClosePrice < 201 ";
            string cond3 = where + "  and  ClosePrice > 250 and  ClosePrice < 301 ";
            var result1 = TwstockDAL.GetListArray(cond1);
            var result2 = TwstockDAL.GetListArray(cond2);
            var result3 = TwstockDAL.GetListArray(cond3);

            int iDays = Convert.ToInt32(chDays);
            DateTime tempRange = DateTime.Parse(TypeChange.ChineseToWestSDate(chDate)).AddDays(iDays * -1);
            string stempRange = (tempRange.Year - 1911).ToString() + tempRange.ToString("MMdd");
            foreach (var item in result1)
            {
                double? dcloseprice = item.ClosePrice;
                bool IsAdd = false;
                where = "";
                where = $" 1=1 and chDate >'{stempRange}' and  chDate <='{chDate}' and StockCode='{ item.StockCode}'";
                var tempResult = TwstockDAL.GetListArray(where);
                foreach (var item2 in tempResult)
                {
                    IsAdd = true;
                    double? dcloseprice2 = item2.ClosePrice;
                    if (dcloseprice2 > 100)
                    {
                        IsAdd = false;
                        break;
                    }
                    decimal dhPrice = decimal.Parse(item2.HightPrice);
                    if (dhPrice > 100)
                    {
                        IsAdd = false;
                        break;
                    }
                }
                if (IsAdd)
                {
                    //確認是否為期貨指數

                    int tempcount = futureStockDAL.CalcCount(string.Format(" Code ='{0}'", item.StockCode));
                    if (tempcount > 0)
                    {
                        result.Add(item);
                    }
                 
                }
            }
            foreach (var item in result2)
            {
                double? dcloseprice = item.ClosePrice;

                bool IsAdd = false;
                where = "";
                where = $" 1=1 and chDate >'{stempRange}' and  chDate <='{chDate}'  and StockCode='{ item.StockCode}'";
                var tempResult = TwstockDAL.GetListArray(where);
                foreach (var item2 in tempResult)
                {
                    IsAdd = true;
                    double? dcloseprice2 = item2.ClosePrice;
                    if (dcloseprice2 > 200)
                    {
                        IsAdd = false;
                        break;
                    }
                    decimal dhPrice = decimal.Parse(item2.HightPrice);
                    if (dhPrice > 200)
                    {
                        IsAdd = false;
                        break;
                    }
                }
                if (IsAdd)
                {
                    //確認是否為期貨指數
                    int tempcount = futureStockDAL.CalcCount(string.Format(" Code ='{0}'", item.StockCode));
                    if (tempcount > 0)
                    {
                        result.Add(item);
                    }
                }
            }
            foreach (var item in result3)
            {
                double? dcloseprice = item.ClosePrice;
                bool IsAdd = false;
                where = "";
                where = $" 1=1 and chDate >'{stempRange}' and  chDate <='{chDate}' and  StockCode='{ item.StockCode}'";
                var tempResult = TwstockDAL.GetListArray(where);
                foreach (var item2 in tempResult)
                {
                    IsAdd = true;
                    double? dcloseprice2 = item2.ClosePrice;
                    if (dcloseprice2 > 300)
                    {
                        IsAdd = false;
                        break;
                    }
                    decimal dhPrice = decimal.Parse(item2.HightPrice);
                    if (dhPrice > 300)
                    {
                        IsAdd = false;
                        break;
                    }
                }
                if (IsAdd)
                {
                    //確認是否為期貨指數
                    int tempcount = futureStockDAL.CalcCount(string.Format(" Code ='{0}'", item.StockCode));
                    if (tempcount > 0)
                    {
                        result.Add(item);
                    }
                }
            }
            return Json(result);
        }
    }
}

WebStockFinder/Views/TwStock/Create.cshtml
@model WinStockFinder.Model.Twstock
@{
    // ViewBag.Title = Model.id == 0 ? "新增Twstock" : "编辑Twstock";
}


<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<script src="https://cdn.90so.net/layui/2.4.5/layui.all.js"></script>
<link href="https://cdn.90so.net/layui/2.4.5/css/layui.css" rel="stylesheet" />


<div class="layui-tab layui-tab-brief" lay-filter="docDemoTabBrief">
    <ul class="layui-tab-title">
        <li class="layui-this">@ViewBag.Title</li>
    </ul>
</div>
<form class="layui-form" action="">
    <div class='layui-form'>
        <table class='layui-table'>
            <tr>
                <th>Id</th>
                <td>
                    @Html.TextBoxFor(a => a.Id, new { @class = "layui-input", lay_verify = "required" })
                </td>
                <th>chDate</th>
                <td>
                    @Html.TextBoxFor(a => a.chDate, new { @class = "layui-input", lay_verify = "required" })
                </td>
            </tr>
            <tr>
                <th>ClosePrice</th>
                <td>
                    @Html.TextBoxFor(a => a.ClosePrice, new { @class = "layui-input", lay_verify = "required" })
                </td>
                <th>UpOrDown</th>
                <td>
                    @Html.TextBoxFor(a => a.UpOrDown, new { @class = "layui-input", lay_verify = "required" })
                </td>
            </tr>
            <tr>
                <th>TradeCount</th>
                <td>
                    @Html.TextBoxFor(a => a.TradeCount, new { @class = "layui-input", lay_verify = "required" })
                </td>
                <th>TradeMoney</th>
                <td>
                    @Html.TextBoxFor(a => a.TradeMoney, new { @class = "layui-input", lay_verify = "required" })
                </td>
            </tr>
            <tr>
                <th>OpenPrice</th>
                <td>
                    @Html.TextBoxFor(a => a.OpenPrice, new { @class = "layui-input", lay_verify = "required" })
                </td>
                <th>HightPrice</th>
                <td>
                    @Html.TextBoxFor(a => a.HightPrice, new { @class = "layui-input", lay_verify = "required" })
                </td>
            </tr>
            <tr>
                <th>LowPrice</th>
                <td>
                    @Html.TextBoxFor(a => a.LowPrice, new { @class = "layui-input", lay_verify = "required" })
                </td>
                <th>StockCode</th>
                <td>
                    @Html.TextBoxFor(a => a.StockCode, new { @class = "layui-input", lay_verify = "required" })
                </td>
            </tr>
            <tr>
                <th>CreateDate</th>
                <td>
                    @Html.TextBoxFor(a => a.CreateDate, new { @class = "layui-input", lay_verify = "required" })
                </td>
                <th></th>
                <td></td>
            </tr>
        </table>


        <div class="layui-form-item">
            <label class='layui-form-label'>&nbsp;</label>
            <div class="layui-input-inline">
                <button id="btn1" class="layui-btn" lay-submit="" lay-filter="demo1">@ViewBag.Title</button>
                @Html.AntiForgeryToken()
                
            </div>
        </div>
    </div>
</form>
<link rel="stylesheet" href="/content/kindeditor/themes/default/default.css" />
<link rel="stylesheet" href="/content/kindeditor/plugins/code/prettify.css" />
<script src="/content/kindeditor/kindeditor-all-min.js"></script>
<script charset="utf-8" src="/content/kindeditor/lang/zh-CN.js"></script>
<script charset="utf-8" src="/content/kindeditor/plugins/code/prettify.js"></script>
<script>
    var pop_index;
    var editor1;
    KindEditor.ready(function (K) {
        editor1 = K.create('#body', {
            cssPath: '/content/kindeditor/plugins/code/prettify.css',
            uploadJson: '/Adnn1n/Home/KE_Upload',
            afterCreate: function () {
                var self = this;
                K.ctrl(document, 13, function () {
                    self.sync();
                    K('form[name=form1]')[0].submit();
                });
                K.ctrl(self.edit.doc, 13, function () {
                    self.sync();
                    K('form[name=form1]')[0].submit();
                });
            }
        });
        prettyPrint();
    });

    /*加载layui编辑器*/
    layui.use(['form', 'layer', 'laydate', 'upload'], function () {
        var form = layui.form;
        var laydate = layui.laydate;
        var upload = layui.upload;
        var layer = layui.layer;
        var $ = layui.jquery;


        var uploadInst = upload.render({
            elem: '#btnimg',
            url: '/Adnn1n/Home/ImgUpload' //上传接口
            , done: function (res) { //上传成功后的回调
                // console.log(res);
                document.getElementById("img1").src = res.data.src;
                document.getElementById("img").value = res.data.src;    //这里的img对应表中的字段，有可能是face也有可能是logo
            }
        });



        //监听提交
        form.on('submit(demo1)', function (data) {
            var url = "/adnn1n/Twstock/add";
            var postdata = data.field;
            //postdata.body = editor1.html();

            $('#btn1').attr("class", "layui-btn layui-btn-disabled");
            $('#btn1').attr("disabled", "disabled");

            pop_index = layer.load(0, {
                shade: [0.3, '#000'] //0.1透明度的白色背景
            });
            $.post(url, postdata, function (data) {
                layer.close(pop_index);
                if (data.code == 0) {
                    layer.msg(data.msg, function () { location.href = "/adnn1n/Twstock/"; })
                } else {
                    layer.msg(data.msg);
                }
            }, 'json')
            return false;
        });

    });</script>

WebStockFinder/Views/TwStock/Index.cshtml
<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/My97DatePicker/WdatePicker.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/My97DatePicker/skin/WdatePicker.css" rel="stylesheet" />
<h3>股票查詢作業</h3>
<div class="form-inline">
    <div class="form-group">
        <label>日期</label>
        <input type="text" class="form-control" id="chDate" name="chDate" onclick="WdatePicker({el:this,dateFmt:'yyyMMdd'})">
    </div>
    <div class="form-group">
        <label>天數</label>
        <input type="text" class="form-control" id="chDays" name="chDays">
    </div>
    <div class="form-group">
        <label>股號</label>
        <input type="text" class="form-control" id="chStock" name="chStock">
    </div>
    <button id="btnsubmit" type="button" class="btn btn-primary" onclick="loadData();">查詢</button>
</div>
<br />
<table class="table table-bordered ">
    <thead>
        <tr>
            <th>管理</th>
            <th>chDate</th>
            <th>ClosePrice</th>
            <th>UpOrDown</th>
            <th>TradeCount</th>
            <th>TradeMoney</th>
            <th>OpenPrice</th>
            <th>HightPrice</th>
            <th>LowPrice</th>
            <th>StockCode</th>
            <th>CreateDate</th>
        </tr>
    </thead>
    <tbody id="tbody"></tbody>
</table>
<script>

    //Load Data function
    function loadData() {

      
        var btn = $("#btnsubmit");
        btn .attr('disabled', true);
        btn.text('資料讀取中....');
        var postdata = getcond();
        var url =  '@Url.Action("Index", "Twstock")';
        debugger;
        $.post(url, postdata, function (json) {

            var html = '';
            $.each(json, function (i, item) {
                // console.log("第" + i + "个元素：");
                //  console.log(blog);
                html += '<tr>';
                html += '    <td>';
           //   html += '        <a href="/Adnn1n/Twstock/Add/' + item.id + '"><i class="layui-icon">&#xe642;</i> 编辑</a>';
                //html += '        <a href="javascript:void(0);" onclick="del(' + item.id + ')"><i class="layui-icon">&#x1006;</i> 删除</a>';
                html += '    </td>';
                html += '    <td>' + item.chDate + '</td>';
                html += '    <td>' + item.ClosePrice + '</td>';
                html += '    <td>' + item.UpOrDown + '</td>';
                html += '    <td>' + item.TradeCount + '</td>';
                html += '    <td>' + item.TradeMoney + '</td>';
                html += '    <td>' + item.OpenPrice + '</td>';
                html += '    <td>' + item.HightPrice + '</td>';
                html += '    <td>' + item.LowPrice + '</td>';
                html += '    <td>' + item.StockCode + '</td>';
                html += '    <td>' + item.CreateDate + '</td>';
                html += '</tr>';
            })
            $('#tbody').html(html);
            btn.attr('disabled', false);
            btn.text('查詢');
        }, 'json');
    }
    /*拼接条件返回postdata*/
    function getcond() {
        var chDate = $("#chDate").val();
        var chDays = $("#chDays").val();
        var chStock = $("#chStock").val();
        var postdata = { chDate: chDate, chDays: chDays, chStock: chStock };
        return postdata;
    }
    $(document).ready(function () {
        loadData();
    });
</script>